/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef MOOS21_PRIVATE_H
#define MOOS21_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"2.1.0.3064"
#define VER_MAJOR	2
#define VER_MINOR	1
#define VER_RELEASE	0
#define VER_BUILD	3064
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	""
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	""

#endif /*MOOS21_PRIVATE_H*/
